services:

  postgres:
    image: postgres:17.4-bookworm
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456'
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - auth-net

networks:
  auth-net:
    driver: bridge

volumes:
  postgresdata:

# docker build -f Dockerfile -t device-api .
# docker-compose -f compose.yaml up -d
