CREATE SCHEMA IF NOT EXISTS device_api;

CREATE TABLE IF NOT EXISTS device (
    id BIGSERIAL NOT NULL,
    name VARCHAR(150) NOT NULL,
    brand VARCHAR(150) NOT NULL,
    state VARCHAR(10) NOT NULL,
    creation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);