spring:
  application:
    name: device-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?createDatabaseIfNotExist=true&currentSchema=device_api
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456} 
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        default-schema: device_api
        formatSql: ${SHOW_SQL:false}

  flyway:
    enabled: true
    locations: db/postgresql
    schemas: device_api
